name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Ensure lib & examples build
        run: pnpm run build
